### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by jullatt** [UniLuFS2020-ReplicationSeminar/23FS_DataM_ClassEx1_BkNwJl#2]
Let's pick a group name and adjust our repo name using it instead of "BkNwJI". Any suggestions?

**Comment by bekurmann** [comment]
GPT-4: 
«Considering your data mining seminar context, I suggest the group name "Data TrioMiners." This name combines the idea of being a trio with a focus on data mining, highlighting the nature of your team and your area of expertise.»

-> maybe just «TrioMiners» ?

**Comment by nigi1992** [comment]
"Trio Miners" sounds good to me. "TrippleX-Miners" if you are looking for something more extreme.

**Comment by jullatt** [comment]
Sounds great! I'll change the repo name.
