### ISSUE TITLE
Can't add images of the ggplots into R Markdown

### ISSUE THREAD

**Issue by nigi1992** [UniLuFS2020-ReplicationSeminar/23FS_DataM_ClassEx1_BkNwJl#3]
I was unable to insert the png images into the R Markdown text. A google and a ChatGPT search didn't help either. ChatGPT suggested the following code, but it gives me error messages: 

In your R Markdown document, add an image to a markdown cell using the following syntax:

css
![alt text] (path/to/image)

Here, alt text is the alternative text that is displayed when the image cannot be loaded, and path/to/image is the file path to the image file.
For example, if you have an image named "myimage.png" saved in a directory called "images" within your project, the syntax to add it to a markdown cell would be:

scss
![My Image] (images/myimage.png)

Any ideas? Alternatively we could just write into R Markdown as text, where one can find the images.

**Comment by jullatt** [comment]
Have you tried to just put the code of the plots into the markdown file (within a code snippet)? It then should render the plots as well into the html file.

**Comment by nigi1992** [comment]
No. I'll try that. thanks

**Comment by nigi1992** [comment]
Did work. Plots can now be viewed from within the R Markdown document. Thanks a lot!
